name: CI
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_TEAM_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  TURBO_TEAM: ${{ secrets.VERCEL_TEAM_ID }}
  REF: ${{ (github.event_name == 'pull_request' && github.base_ref) || github.ref_name }}
on:
  - pull_request
  - push

jobs:
  Checkstyle-Lint-Build:
    runs-on: ubuntu-latest
    if: ${{ github.repository == 'DevDogs-UGA/Community-Resource-Forum' }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
      - name: Install dependencies
        run: pnpm install --ignore-scripts
      - name: Pull Vercel Preview Build Configuration
        run: |
          pnpm vercel pull ${{ env.ENV_CONFIG }} --yes --git-branch=${{ github.base_ref }} --token=${{ secrets.VERCEL_TOKEN }}
          pnpm vercel env pull ${{ env.ENV_CONFIG }} --token=${{ secrets.VERCEL_TOKEN }} .env
          echo "BASE_URL=https://${{ (env.REF == 'main' && 'community-resource-forum.vercel.app') || 'community-resource-forum-$(git rev-parse --short=7 HEAD)-devdogs.vercel.app' }}" >> .env
        env:
          ENV_CONFIG: ${{ (env.REF == 'main' && '--environment=production') || format('--environment=preview --git-branch={0}', env.REF) }}
      - name: Validate Formatting and Linting
        run: pnpm turbo lint prettier
      - name: Build Project Artifacts
        run: pnpm vercel build ${{ (env.REF == 'main' && '--prod') || ' ' }} --token=${{ secrets.VERCEL_TOKEN }}
      - name: Migration Dry Run
        if: ${{ github.event_name == 'pull_request' }}
        run: pnpm db:migrate --dry-run
      - name: Deploy Project
        if: ${{ github.event_name == 'push' }}
        run: |
          pnpm db:migrate --auto-approve
          pnpm vercel deploy ${{ (env.REF == 'main' && '--prod') || ' ' }} --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
